name: Perform Manual Backport Audit

on:
  workflow_dispatch:
  schedule:
  - cron: '0 16 * * 3'

jobs:
  audit:
    name: Perform Manual Backport Audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # tag: v3.3.0
    - name: Setup Node.js
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c  # tag: v3.6.0
      with:
        node-version: lts/*
    - name: Install Dependencies
      run: npm install
    - name: Check PRs Needing Manual Backport
      run: node entrypoint.js
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        UNRELEASED_GITHUB_APP_CREDS: ${{ secrets.UNRELEASED_GITHUB_APP_CREDS }}
        ACTION_TYPE: 'needs-manual'